INFLUXDB_ADDRESS = ''
INFLUXDB_USER = ''
INFLUXDB_PASSWORD = ''
INFLUXDB_DATABASE = ''

MQTT_ADDRESS = ''
MQTT_PORT = 18801
MQTT_USER = ''
MQTT_PASSWORD = ''
MQTT_TOPIC = ''
MQTT_CLIENT_ID = 'MQTTInfluxDBBridge'
